recon_engine:
  name: Generic_Matching
  no_of_legs: 2
  scheduler:
    type: scheduled
    cron_expression: "0 0 * * *"
  matching_engine:
    no_of_stages: 3
    stage_config:
      - stage_number: 1
        recon_parameters:
          - col1
          - col2
          - col3
      - stage_number: 2
        recon_parameters:
          - col4
          - col5
          - col6
      - stage_number: 3
        recon_parameters:
          - col7
          - col8
          - col9
  leg_sources:
    - source_1:
        type: mq_topic
        name: Q1
      source_2:
        type: rest_api
        url: "/rest"
  notifications:
    - name: data_ingestion_notification_1
      lambda_arn: arn:aws:lambda:us-east-1:123456789012:function:data_ingestion_function_1
    - name: data_ingestion_notification_2
      lambda_arn: arn:aws:lambda:us-east-1:123456789012:function:data_ingestion_function_2
    - name: enrichment_notification_1
      lambda_arn: arn:aws:lambda:us-east-1:123456789012:function:enrichment_function_leg_1
    - name: enrichment_notification_2
      lambda_arn: arn:aws:lambda:us-east-1:123456789012:function:enrichment_function_leg_2
    - name: matching_notification
      lambda_arn: arn:aws:lambda:us-east-1:123456789012:function:matching_function
  enrichment_process:
    leg_1:
      emr_job:
        name: data_enrichment_process_leg_1
        s3_location: s3://processing-bucket/enrichment/leg_1/
    leg_2:
      emr_job:
        name: data_enrichment_process_leg_2
        s3_location: s3://processing-bucket/enrichment/leg_2/
  matching_process:
    emr_job:
      name: matching_engine
      s3_location: s3://conformed-bucket/matching_results/
  post_processing:
    - name: EMR job post_processing_step_1
      purpose: "Purpose of EMR job post processing step 1"
      emr_job:
        name: post_processing_step_1
        s3_location: s3://post-processing-bucket/output1/
    - name: EMR job post_processing_step_2
      purpose: "Purpose of EMR job post processing step 2"
      emr_job:
        name: post_processing_step_2
        s3_location: s3://post-processing-bucket/output2/
